CC= g++
FLAGS = -g -Wall -c
INCLUDE_DIR_SDL = -I/usr/include/SDL2
LIBS_SDL = -lSDL2 -lSDL2_ttf -lSDL2_image
EXE = perso 

#a faire

all : $(EXE)

personnage :  Personnage.h
$(CC) $(FLAGS) Personnage.cpp 



